# Numpy and vectorisation

In [2]:
import numpy as np
import time

In [3]:
#numpy documentation at NumPy.org
#numpy is indexable ie.. every value has an index
#vector creation
a = np.zeros(4)
print(f"np.zeros(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4)
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4): a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.11506877 0.23565611 0.90288383 0.48526751], a shape = (4,), a data type = float64


In [4]:
#numpy with memory and filled arrays

#integer values from 0 to 3
a = np.arange(4)
print(f"np.arange(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

#random values could be float as well
a = np.random.rand(4)
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4): a = [0 1 2 3], a shape = (4,), a data type = int64
np.random.rand(4): a = [0.06883269 0.69589927 0.35208151 0.49270405], a shape = (4,), a data type = float64


In [5]:
#manual values in a numpy routines
a = np.array([5,7,8,9])
print(f"np.array([5,7,8,9]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

#manula float values 
a = np.array([2.3, 4.6, 1.2, 7.8])
print(f"np.array([2.3, 4.6, 1.2, 7.8]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,7,8,9]): a = [5 7 8 9], a shape = (4,), a data type = int64
np.array([2.3, 4.6, 1.2, 7.8]): a = [2.3 4.6 1.2 7.8], a shape = (4,), a data type = float64


# operations on vectors

In [6]:
#vectors indexing
a = np.arange(10) #values from 0 to 9
#accessing an element
print(f"a[2] shape = {a[2].shape}, a[2] = {a[2]}, accessing an element returns a scalar")

#accessing the last element
print(f"a[-1] shape = {a[-1].shape}, a[-1] = {a[-1]}, accessing an element returns a scalar")

#for the out of bound index
try:
    c = a[10]
except Exception as e:
    print("Error message is:")
    print(e)

a[2] shape = (), a[2] = 2, accessing an element returns a scalar
a[-1] shape = (), a[-1] = 9, accessing an element returns a scalar
Error message is:
index 10 is out of bounds for axis 0 with size 10


In [7]:
#slicing in vectors
#creates an array of indices using a set of three values (start:stop:step)

a = np.arange(10)

#accessing 5 consecutive elements with difference of 1
c = a[2:7:1]
print(f"a[2:7:1] : {c}")

#accessing 3 elements seperated by 2
c = a[2:7:2]
print(f"a[2:7:2] : {c}")

#accessing all elements index 3 and above
c= a[3:]
print(f"a[3:] : {c}")

#accessing all elements below index 3
c = a[:3]
print(f"a[:3] : {c}")

#accessing all elements
c= a[:]
print(f"a[:] : {c}")

a[2:7:1] : [2 3 4 5 6]
a[2:7:2] : [2 4 6]
a[3:] : [3 4 5 6 7 8 9]
a[:3] : [0 1 2]
a[:] : [0 1 2 3 4 5 6 7 8 9]


In [8]:
#single vector operations
a = np.arange(10)
print(f"np.arange(10) : {a}")

#negative of elements
b = -a
print(f"negative of a : {b}")

#sum of all elements
c = np.sum(a)
print(f"Sum of all elements in a : {c}")

#mean of an array
d = np.mean(a)
print(f"Mean of all elements: {d}")

#square of all elements
e = a ** 2
print(f"Square of all elements in a: {e}")

np.arange(10) : [0 1 2 3 4 5 6 7 8 9]
negative of a : [ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
Sum of all elements in a : 45
Mean of all elements: 4.5
Square of all elements in a: [ 0  1  4  9 16 25 36 49 64 81]


In [9]:
#element wise vector operation
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])
print(f"vector sum of the arrays is: {a+b}")

vector sum of the arrays is: [0 0 6 8]


In [10]:
#this won't work as they have different shapes 
c = np.array([3,4])
try:
    d = b + c
except Exception as e:
    print("The error is:")
    print(e)

The error is:
operands could not be broadcast together with shapes (4,) (2,) 


In [11]:
#Scalar vector operations
a = np.array([1,2,3,4])
b = 5 * a
print(f"Scalar product is: {b}")

Scalar product is: [ 5 10 15 20]


In [12]:
#Function to determine the dot product of two vectors
def my_dot(a,b):
    x = 0
    
    for i in range (a.shape[0]):
        x += a[i] * b[i]
        
    return x

In [13]:
x1 = np.array([1,2,3,4])
x2 = np.array([-1,2,3,2])

print(f"Dot product is: {my_dot(x1, x2)}")

Dot product is: 20


In [14]:
#Same process using np.dot method

x3 = np.dot(x1,x2)
print(f"Dot product using np.dot() method is: {x3}, Shape is {x3.shape}")

Dot product using np.dot() method is: 20, Shape is ()


In [15]:
np.random.seed(1)

a = np.random.rand(10000000) #6zeroes
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(f"Time taken to calculate dot product is: {1000*(toc - tic)} ms")
print(f"Product is: {c}")

Time taken to calculate dot product is: 9.584903717041016 ms
Product is: 2501072.581681195


In [16]:
del (a)

In [17]:
del (b)

In [18]:
x = np.array([[1],[2],[3],[4]])
y = np.array([6])
print(f"Shape of x is: {x.shape}")
print(f"Shape of x[1] is: {x[1].shape}")

Shape of x is: (4, 1)
Shape of x[1] is: (1,)


# matrices operations

In [20]:
#create matrix
# 1x5 matrix
a = np.zeros((1,5))
print(f"Shape of a is: {a.shape} and a is: {a}")

Shape of a is: (1, 5) and a is: [[0. 0. 0. 0. 0.]]


In [21]:
# 4 row X 1 matrix
a = np.zeros((4,1))
print(f"Shape of a is: {a.shape}, and a is {a}")

Shape of a is: (4, 1), and a is [[0.]
 [0.]
 [0.]
 [0.]]


In [23]:
#5x4 matrix
a = np.zeros((5,4))
print(f"a is : {a} and its shape is : {a.shape}")

a is : [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] and its shape is : (5, 4)


In [25]:
#random sample
a = np.random.random_sample((5,4))
print(f"Random matrix is: {a} and its shape is {a.shape}")

Random matrix is: [[0.5669563  0.36607953 0.12254939 0.41590761]
 [0.83186916 0.49357909 0.90762403 0.71371965]
 [0.24246182 0.19614305 0.71120633 0.17314952]
 [0.21576912 0.71609203 0.89638213 0.17019093]
 [0.71807747 0.89104422 0.57643061 0.63979044]] and its shape is (5, 4)
