# Multiple Linear Regression

In [61]:
'''To support multiple input features
Before we have seen only one input feature
This time we are going to take a look at multiple features
Using numpy '''

'To support multiple input features\nBefore we have seen only one input feature\nThis time we are going to take a look at multiple features\nUsing numpy '

In [62]:
#numpy and matplot library is going to be used 
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')

#reduced display precion on numpy arrays
np.set_printoptions(precision = 2)

In [63]:
#create a problem statement table
#here it has 4 features 
#size in sq ft, # bedrooms, # floors and age of home
X_train = np.array([[2104,5,1,45], [1416,3,2,40], [852,2,1,35]])
y_train = np.array([460, 232, 178])

In [64]:
#here X is the vector containing input data samples
#here y_train is the output values in our training data set

#shape of X and y is
print(f"Shape of X is: {X_train.shape}, type of X_train is: {type(X_train)} and \nX_train is : \n{X_train}")

Shape of X is: (3, 4), type of X_train is: <class 'numpy.ndarray'> and 
X_train is : 
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]


In [65]:
#parameters w1, w2, w3 and w4 based on the features
#b is the scalar parameter
b_init = 785.1811367994083
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])

print(f"w_init shape is: {w_init.shape} and its type is {type(w_init)}, and b_init type: {type(b_init)}")

w_init shape is: (4,) and its type is <class 'numpy.ndarray'>, and b_init type: <class 'float'>


In [66]:
#prediction element by element when there is multiple features
def predict_single_loop(x, w, b):
    p = 0
    
    for i in range (x.shape[0]):
        p_i = w[i]*x[i]
        p = p + p_i
    p = p + b
    
    return p

In [67]:
#Extract a single row and make prediction
x_vec = X_train[0,:]
print(f"X vector shape: {x_vec.shape} and X vector value: {x_vec}")

#make a prediction
f_wb = predict_single_loop(x_vec, w_init, b_init)
print(f"Predicted output is: {f_wb} and shape: {f_wb.shape}")

X vector shape: (4,) and X vector value: [2104    5    1   45]
Predicted output is: 459.9999976194083 and shape: ()


# Same can be done using dot product of Vectors

In [68]:
#dot product of vectors consumes less time as compared to the row wise element multiplication'
#using arrays

def predict(x, w, b):
    
    p = np.dot(x, w) + b
    
    return p

In [69]:
#make the prediction for the same row
f_wb = predict(x_vec, w_init, b_init)
print(f"Predicted output is: {f_wb} and shape is {f_wb.shape}")

Predicted output is: 459.9999976194083 and shape is ()


In [70]:
#Compute cost with multiple variables J(w,b) = (1/2m)*(f w,b(x(i)) - y(i))^2)

def compute_cost(X, y, w, b):
    cost = 0.0
    #training data 'm'
    m = X.shape[0]
    
    for i in range(m):
        f_wb_i = np.dot(X[i], w) + b
        cost = cost + (f_wb_i - y[i])**2
        
    cost = cost / (2*m)
    
    return cost

In [71]:
#calculate cost 

cost = compute_cost(X_train, y_train, w_init, b_init)
print(f"Cost at optimal w: {cost}")

Cost at optimal w: 1.5578904045996674e-12
